tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-eid"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "vitorgalvao/tiny-scripts"
brew "ansible"
brew "awscli"
brew "carthage"
brew "circleci"
brew "docker"
brew "docker-compose"
brew "duck"
brew "fswatch"
brew "git"
brew "git-lfs"
brew "hub"
brew "little-cms2"
brew "imagemagick"
brew "mas"
brew "php"
brew "pngquant"
brew "postgresql", restart_service: true
brew "pyenv"
brew "r"
brew "ruby-build"
brew "rbenv"
brew "rsync"
brew "tree"
brew "unison"
brew "wp-cli"
brew "yarn"
brew "zsh"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "adobe-creative-cloud"
cask "atom"
cask "avocode"
cask "brave-browser"
cask "chatwork"
cask "craftmanager"
cask "cyberduck"
cask "docker"
cask "dropbox"
cask "duet"
cask "evernote"
cask "figma"
cask "firefox"
cask "flinto"
cask "font-foundation-icons"
cask "font-ionicons"
cask "font-material-icons"
cask "font-noto-sans-cjk-jp"
cask "font-ricty-diminished"
cask "fontbase"
cask "framer"
cask "framer-x"
cask "franz"
cask "genymotion"
cask "gitbook-editor"
cask "gitter"
cask "glyphs"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "i1profiler"
cask "imageoptim"
cask "invisionsync"
cask "iterm2"
cask "jasper"
cask "kactus"
cask "kindle"
cask "marvel"
cask "metabase"
cask "mono-mdk"
cask "noodl"
cask "notion"
cask "orange"
cask "origami-studio"
cask "pgadmin4"
cask "phpstorm"
cask "plant"
cask "principle"
cask "react-studio"
cask "recordit"
cask "rightfont"
cask "rstudio"
cask "sequel-pro"
cask "sketch"
cask "skype"
cask "sourcetree"
cask "spotify"
cask "station"
cask "stride"
cask "sublime-text"
cask "teamsql"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vivaldi"
cask "webpquicklook"
cask "zeplin"
cask "zoomus"
mas "com.apple.dt.Xcode", id: 497799835
mas "com.apple.garageband10", id: 682658836
mas "com.apple.iMovieApp", id: 408981434
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "com.atlassian.trello", id: 1278508951
mas "com.devhd.feedly.osx", id: 865500966
mas "com.francescodilorenzo.Mailbro", id: 1053031090
mas "com.ideasoncanvas.mindnode.macos", id: 1289197285
mas "com.pixelmatorteam.pixelmator", id: 407963104
mas "com.pixelmatorteam.pixelmator.x", id: 1289583905
mas "com.readitlater.PocketMac", id: 568494494
mas "com.rockysandstudio.Disk-Diag", id: 672206759
mas "com.seriflabs.affinitydesigner", id: 824171161
mas "com.sociomedia.Textwell.Mac", id: 905944937
mas "com.tinyspeck.slackmacgap", id: 803453959
mas "com.type-fu.TypeFu", id: 509818877
mas "cx.c3.theunarchiver", id: 425424353
mas "de.milchimgemuesefach.Display-Menu", id: 549083868
mas "io.replia.Replia", id: 988307015
mas "jp.co.ndc.stone", id: 1230288277
mas "jp.naver.line.mac", id: 539883307
